name: Pack Release Zip
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove GitHub CI/CD
        run: rm -r .github/
      - name: Remove gitignore
        run: rm .gitignore
      - name: Remove CI
        run: rm -r CI/
      - name: Remove tests
        run: rm -r tests/
      - name: Remove test
        run: rm -r test/
      - name: Remove Dicto
        run: rm -r dicto/
      - name: Remove babelrc
        run: rm .babelrc.json
      - name: Remove eslintrc
        run: rm .eslintrc.json
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 7.4
          version: 2.2.x
          args:
      - name: Pack Release Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -ry ILIAS-${{ github.event.release.tag_name }}.zip .
      - name: Pack Release Tar
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: zcvf
          outPath: ILIAS-${{ github.event.release.tag_name }}.tar.gz
